### PR TITLE
Update Dockerfile to fix `pysam==0.7.5` requirement

### PR DESCRIPTION
**Pull request by die4live**
Download the specific version 0.7.5 of pysam from source and install it.

### CODE REVIEW

**Comment by die4live** [comment]
It seems weird that the `wget` command is not executed when build this Dockerfile from travis-ci log:<

**Comment by LeeTL1220** [comment]
I am about to make pysam 0.9.0 the requirement.  I'll update the dockerfile as well.

**Comment by LeeTL1220** [comment]
If v1.9.0.0 (releasing soon) does not fix this, please say something.

**Comment by LeeTL1220** [comment]
Not going to merge....  Closed by #344

**Pull request closed without merging**
